[package]
name = "aoc15"
version = "0.1.0"
edition = "2024"

[dependencies]
linkme = "0.3.35"
rayon = "1.11.0"
md5 = "0.8.0"
nom = "8.0.0"
rustc-hash = "2.1.1"
serde_json = "1.0.145"
serde = { version = "1.0.228", features = ["derive"] }
